version: "3.7"

networks:
    kong-net:
        
services:
    #######################################
    # proxy: reverseproxy
    #######################################
    nginx-proxy:
        image: jwilder/nginx-proxy
        networks:
          - kong-net  
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
